#!/bin/bash

if pgrep bspwm || pgrep dwm ; then
    maim | xclip -selection clipboard -t image/png
    xclip -selection clipboard -o > $(xdg-user-dir PICTURES)/$(date +'screenshot_%Y-%m-%d-%H%M%S.png')
else
    grim - | wl-copy
    wl-copy -o > $(xdg-user-dir PICTURES)/$(date +'screenshot_%Y-%m-%d-%H%M%S.png')
fi
