#!/bin/sh

pactl set-sink-mute @DEFAULT_SINK@ toggle

message=""
if [ "$(pacmd list-sinks | awk '/muted/ { print $2 }')" = "yes" ]; then
    message="Muted"
else
    message="Unmuted"
fi

dunstify Volume $message
