#!/bin/bash

pactl set-sink-volume 0 +5%

volume=`pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'`

dunstify Volume ${volume}%
