#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc ~/.config/sxhkd/keys.conf &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color \#8f15ed
bspc config focused_border_color \#00c5ff
bspc config focus_follows_pointer true

~/.config/autostart.sh
